# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('createById', models.CharField(blank=True, default='', max_length=36)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
